### ISSUE TITLE
Jekyll throws error on jekyll serve - "Cannot load such file -- jekyll/version (LoadError)"

### ISSUE THREAD

**Issue by zachcowell** [ellekasai/shiori#15]
Whenever I do `jekyll serve` I get the following error:

```
WARN: Unresolved specs during Gem::Specification.reset:
      pygments.rb (~> 0.6.0)
      redcarpet (~> 3.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/bin/jekyll:21:in `block in <top (required)>': cannot load such file -- jekyll/version (LoadError)
    from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary.rb:18:in `program'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
    from /usr/bin/jekyll:23:in `load'
    from /usr/bin/jekyll:23:in `<main>'
```

I'm a little new to Jekyll / gems. I did a little research and found out that if I remove the Gemfile, the `jekyll serve` works just fine. I am using Jekyll version 2.5.3

I will likely not be hosting my Jekyll app on github pages, so do I really need this dependency?

**Comment by vaibhavsinghal87** [comment]
I faced the same issue but when i ran **bundle exec jekyll serve** instead of **jekyll serve** from the terminal, all worked fine.

**Comment by Shikkic** [comment]
Just ran into this today had to do `bundle exec jekyll serve` referenced [here](https://github.com/jekyll/jemoji/issues/32)
