### ISSUE TITLE
Ability to define custom color

### ISSUE THREAD

**Issue by chibicode** [ellekasai/shiori#3]
Would it be possible to add a custom color on  `_data/theme.yml`?

``` yaml
color: "#f00"
```

Then it should use this color for the theme?

![screenshot_2014-09-30_at_10_56_34_am](https://cloud.githubusercontent.com/assets/992008/4463448/279ea928-48cb-11e4-8840-d45395ecc220.png)

**Comment by janbiasi** [comment]
**Yes it is possible;** add your own color SCSS variable to <code>/stylesheets/shiori.scss</code> and you'll be able to use it in the <code>_data/theme.yml</code> file. So it would finally look like that;

## 

##### shiori.scss

``` scss
...
$myColor: #f00;
...
```

##### theme.yml

``` yml
..
color: myColor
...
```

**Comment by chibicode** [comment]
:+1: Thanks!

**Comment by janbiasi** [comment]
No problem :smiley:
