### ISSUE TITLE
Would you please support Categories in the Archive Page?

### ISSUE THREAD

**Issue by gmlang** [ellekasai/shiori#4]
I love your theme and just installed it for my blog. One feature I really want to have is to list the categories of each post on the archive page, and when user clicks on the category, it will direct her to a page of all posts under that category. 

Would you please add this feature?

Thanks so much

**Comment by ellekasai** [comment]
If you want to make category pages, you must manually push the generated `_site` directory to GitHub. If you're still okay with that, [@alextsui05](https://github.com/alextsui05) made an [excellent demo and tutorial for category pages](http://alextsui05.github.io/shiori/categories-in-shiori/). You can see his code on [this pull request](https://github.com/ellekasai/shiori/pull/11).
