### ISSUE TITLE
Show Link to /archive below posts on index.html

### ISSUE THREAD

**Issue by chibicode** [ellekasai/shiori#7]
I think it makes sense to show a link to `/archive` below posts on `index.html` to let users know that there are more articles than what's listed here. It also makes sense to show the total number of posts (example: `View Archive (10 Articles)`)

Maybe it makes sense to use **block level** button (`"btn btn-default btn-lg btn-block`):
http://getbootstrap.com/css/#buttons-sizes

![pasted_image_12_5_14__1_41_pm](https://cloud.githubusercontent.com/assets/992008/5323410/9559764a-7c84-11e4-953e-7bc26fbbbc2a.png)

**Comment by alextsui05** [comment]
Why not use the paginator in Jekyll and add links to read older/newer posts? For example, I'm using Shiori for my developer's journal [1] and hacked next/previous links from the post layout. Maybe you can make it prettier.

[1] http://alextsui05.github.io/

**Comment by ellekasai** [comment]
Thank you for the issue :) I added.
